username: wischahaha@outlook.com
password: zhuqy.ziyouxie
phone_number: 1836857896

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer
- <position title 2>
- <position title 3>


locations:
- Michigan
- Remote

salary: 120,000
rate: 60
# --------- Optional Parameters -------
uploads:
  Resume: 'C:\Users\<user>\Documents\resume.docx'
  Cover Letter: 'C:\Users\<user>\Documents\cover letter.docx'
  #Photo: # PATH TO photo


output_filename:
- # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore
