username: wischahaha@outlook.com
password: zhuqy.ziyouxie
phone_number: 1836857896

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer
- <position title 2>
- <position title 3>


locations:
- Michigan
- Remote

salary: 60,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: './cv.pdf'
  Cover Letter: './cl.pdf'
  #Photo: # PATH TO photo


output_filename:
- './out.csv'

# blacklist:
# - # Company names you want to ignore
