username: wischahaha@outlook.com
password: zhuqy.ziyouxie
phone_number: 1836857896

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer


locations:
- Michigan
- Remote

salary: 60,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cv.pdf
  Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo


output_filename:
- /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/out.csv

# blacklist:
# - # Company names you want to ignore
