username: 
password: 

positions:
- # positions you want to search for
- # Another position you want to search for
- # A third position you want to search for

locations:
- # Location you want to search for
- # A second location you want to search in 

cover_letter_loctn:
- # '/home/PATH_TO_FILE' 

output_filename:
- # PATH TO OUTPUT FILE (default output.csv)